
package com.nms.ws.checksubscriber;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CHARGING", targetNamespace = "NMSCGW", wsdlLocation = "http://203.128.246.85/NMS.asmx?WSDL")
public class CHARGING
    extends Service
{

    private final static URL CHARGING_WSDL_LOCATION;
    private final static WebServiceException CHARGING_EXCEPTION;
    private final static QName CHARGING_QNAME = new QName("NMSCGW", "CHARGING");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://203.128.246.85/NMS.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHARGING_WSDL_LOCATION = url;
        CHARGING_EXCEPTION = e;
    }

    public CHARGING() {
        super(__getWsdlLocation(), CHARGING_QNAME);
    }

    public CHARGING(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHARGING_QNAME, features);
    }

    public CHARGING(URL wsdlLocation) {
        super(wsdlLocation, CHARGING_QNAME);
    }

    public CHARGING(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHARGING_QNAME, features);
    }

    public CHARGING(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CHARGING(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CHARGINGSoap
     */
    @WebEndpoint(name = "CHARGINGSoap")
    public CHARGINGSoap getCHARGINGSoap() {
        return super.getPort(new QName("NMSCGW", "CHARGINGSoap"), CHARGINGSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CHARGINGSoap
     */
    @WebEndpoint(name = "CHARGINGSoap")
    public CHARGINGSoap getCHARGINGSoap(WebServiceFeature... features) {
        return super.getPort(new QName("NMSCGW", "CHARGINGSoap"), CHARGINGSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHARGING_EXCEPTION!= null) {
            throw CHARGING_EXCEPTION;
        }
        return CHARGING_WSDL_LOCATION;
    }

}
