
package com.nms.ws.checksubscriber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CHARGINGSoap", targetNamespace = "NMSCGW")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CHARGINGSoap {


    /**
     * 
     * @param username
     * @param msisdn
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckBalance", action = "NMSCGW/CheckBalance")
    @WebResult(name = "CheckBalanceResult", targetNamespace = "NMSCGW")
    @RequestWrapper(localName = "CheckBalance", targetNamespace = "NMSCGW", className = "com.nms.checksub.CheckBalance")
    @ResponseWrapper(localName = "CheckBalanceResponse", targetNamespace = "NMSCGW", className = "com.nms.checksub.CheckBalanceResponse")
    public String checkBalance(
        @WebParam(name = "username", targetNamespace = "NMSCGW")
        String username,
        @WebParam(name = "password", targetNamespace = "NMSCGW")
        String password,
        @WebParam(name = "msisdn", targetNamespace = "NMSCGW")
        String msisdn);

    /**
     * 
     * @param userID
     * @param username
     * @param msisdn
     * @param shortcode
     * @param password
     * @param timeout
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "NMSCGW/extDebit")
    @WebResult(name = "extDebitResult", targetNamespace = "NMSCGW")
    @RequestWrapper(localName = "extDebit", targetNamespace = "NMSCGW", className = "com.nms.checksub.ExtDebit")
    @ResponseWrapper(localName = "extDebitResponse", targetNamespace = "NMSCGW", className = "com.nms.checksub.ExtDebitResponse")
    public String extDebit(
        @WebParam(name = "username", targetNamespace = "NMSCGW")
        String username,
        @WebParam(name = "password", targetNamespace = "NMSCGW")
        String password,
        @WebParam(name = "UserID", targetNamespace = "NMSCGW")
        String userID,
        @WebParam(name = "msisdn", targetNamespace = "NMSCGW")
        String msisdn,
        @WebParam(name = "Shortcode", targetNamespace = "NMSCGW")
        String shortcode,
        @WebParam(name = "timeout", targetNamespace = "NMSCGW")
        int timeout);

    /**
     * 
     * @param userID
     * @param username
     * @param desc
     * @param msisdn
     * @param shortcode
     * @param password
     * @param timeout
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "NMSCGW/extDebit2")
    @WebResult(name = "extDebit2Result", targetNamespace = "NMSCGW")
    @RequestWrapper(localName = "extDebit2", targetNamespace = "NMSCGW", className = "com.nms.checksub.ExtDebit2")
    @ResponseWrapper(localName = "extDebit2Response", targetNamespace = "NMSCGW", className = "com.nms.checksub.ExtDebit2Response")
    public String extDebit2(
        @WebParam(name = "username", targetNamespace = "NMSCGW")
        String username,
        @WebParam(name = "password", targetNamespace = "NMSCGW")
        String password,
        @WebParam(name = "userID", targetNamespace = "NMSCGW")
        String userID,
        @WebParam(name = "msisdn", targetNamespace = "NMSCGW")
        String msisdn,
        @WebParam(name = "shortcode", targetNamespace = "NMSCGW")
        String shortcode,
        @WebParam(name = "timeout", targetNamespace = "NMSCGW")
        int timeout,
        @WebParam(name = "desc", targetNamespace = "NMSCGW")
        String desc);

    /**
     * 
     * @param userID
     * @param username
     * @param desc
     * @param msisdn
     * @param contentSite
     * @param shortcode
     * @param contentName
     * @param password
     * @param timeout
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "NMSCGW/extDebit4WAP")
    @WebResult(name = "extDebit4WAPResult", targetNamespace = "NMSCGW")
    @RequestWrapper(localName = "extDebit4WAP", targetNamespace = "NMSCGW", className = "com.nms.checksub.ExtDebit4WAP")
    @ResponseWrapper(localName = "extDebit4WAPResponse", targetNamespace = "NMSCGW", className = "com.nms.checksub.ExtDebit4WAPResponse")
    public String extDebit4WAP(
        @WebParam(name = "username", targetNamespace = "NMSCGW")
        String username,
        @WebParam(name = "password", targetNamespace = "NMSCGW")
        String password,
        @WebParam(name = "userID", targetNamespace = "NMSCGW")
        String userID,
        @WebParam(name = "msisdn", targetNamespace = "NMSCGW")
        String msisdn,
        @WebParam(name = "shortcode", targetNamespace = "NMSCGW")
        String shortcode,
        @WebParam(name = "timeout", targetNamespace = "NMSCGW")
        int timeout,
        @WebParam(name = "desc", targetNamespace = "NMSCGW")
        String desc,
        @WebParam(name = "ContentName", targetNamespace = "NMSCGW")
        String contentName,
        @WebParam(name = "ContentSite", targetNamespace = "NMSCGW")
        String contentSite);

    /**
     * 
     * @param userID
     * @param s2
     * @param username
     * @param transactionId
     * @param desc
     * @param msisdn
     * @param contentSite
     * @param secret
     * @param shortcode
     * @param contentName
     * @param timeout
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "NMSCGW/extDebit4WAP2")
    @WebResult(name = "extDebit4WAP2Result", targetNamespace = "NMSCGW")
    @RequestWrapper(localName = "extDebit4WAP2", targetNamespace = "NMSCGW", className = "com.nms.checksub.ExtDebit4WAP2")
    @ResponseWrapper(localName = "extDebit4WAP2Response", targetNamespace = "NMSCGW", className = "com.nms.checksub.ExtDebit4WAP2Response")
    public String extDebit4WAP2(
        @WebParam(name = "username", targetNamespace = "NMSCGW")
        String username,
        @WebParam(name = "secret", targetNamespace = "NMSCGW")
        String secret,
        @WebParam(name = "userID", targetNamespace = "NMSCGW")
        String userID,
        @WebParam(name = "msisdn", targetNamespace = "NMSCGW")
        String msisdn,
        @WebParam(name = "shortcode", targetNamespace = "NMSCGW")
        String shortcode,
        @WebParam(name = "timeout", targetNamespace = "NMSCGW")
        int timeout,
        @WebParam(name = "Desc", targetNamespace = "NMSCGW")
        String desc,
        @WebParam(name = "ContentName", targetNamespace = "NMSCGW")
        String contentName,
        @WebParam(name = "ContentSite", targetNamespace = "NMSCGW")
        String contentSite,
        @WebParam(name = "S2", targetNamespace = "NMSCGW")
        String s2,
        @WebParam(name = "TransactionId", targetNamespace = "NMSCGW")
        String transactionId);

    /**
     * 
     * @param username
     * @param shortCode
     * @param msisdn
     * @param password
     * @param smsBody
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SubmitSMS", action = "NMSCGW/SubmitSMS")
    @WebResult(name = "SubmitSMSResult", targetNamespace = "NMSCGW")
    @RequestWrapper(localName = "SubmitSMS", targetNamespace = "NMSCGW", className = "com.nms.checksub.SubmitSMS")
    @ResponseWrapper(localName = "SubmitSMSResponse", targetNamespace = "NMSCGW", className = "com.nms.checksub.SubmitSMSResponse")
    public String submitSMS(
        @WebParam(name = "Username", targetNamespace = "NMSCGW")
        String username,
        @WebParam(name = "Password", targetNamespace = "NMSCGW")
        String password,
        @WebParam(name = "ShortCode", targetNamespace = "NMSCGW")
        String shortCode,
        @WebParam(name = "Msisdn", targetNamespace = "NMSCGW")
        String msisdn,
        @WebParam(name = "SMSBody", targetNamespace = "NMSCGW")
        String smsBody);

    /**
     * 
     * @param username
     * @param password
     * @param ip
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GETMSISDN", action = "NMSCGW/GETMSISDN")
    @WebResult(name = "GETMSISDNResult", targetNamespace = "NMSCGW")
    @RequestWrapper(localName = "GETMSISDN", targetNamespace = "NMSCGW", className = "com.nms.checksub.GETMSISDN")
    @ResponseWrapper(localName = "GETMSISDNResponse", targetNamespace = "NMSCGW", className = "com.nms.checksub.GETMSISDNResponse")
    public String getmsisdn(
        @WebParam(name = "username", targetNamespace = "NMSCGW")
        String username,
        @WebParam(name = "password", targetNamespace = "NMSCGW")
        String password,
        @WebParam(name = "IP", targetNamespace = "NMSCGW")
        String ip);

    /**
     * 
     * @param username
     * @param msisdn
     * @param secret
     * @param code
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SETCRBT", action = "NMSCGW/SETCRBT")
    @WebResult(name = "SETCRBTResult", targetNamespace = "NMSCGW")
    @RequestWrapper(localName = "SETCRBT", targetNamespace = "NMSCGW", className = "com.nms.checksub.SETCRBT")
    @ResponseWrapper(localName = "SETCRBTResponse", targetNamespace = "NMSCGW", className = "com.nms.checksub.SETCRBTResponse")
    public String setcrbt(
        @WebParam(name = "USERNAME", targetNamespace = "NMSCGW")
        String username,
        @WebParam(name = "SECRET", targetNamespace = "NMSCGW")
        String secret,
        @WebParam(name = "MSISDN", targetNamespace = "NMSCGW")
        String msisdn,
        @WebParam(name = "CODE", targetNamespace = "NMSCGW")
        String code);

}
